genz134 pali verification
CodelineAtyab/genz-todo-list-app pull request #106
Opened 2024-03-12 06:44 UTC by Sughiya-AlSaid

2024-03-12 06:46 UTC, HaithamAlMaamari submitted a review, later dismissed

2024-03-12 06:46 UTC, Alhasan-AJ submitted a review, later dismissed

2024-03-12 06:52 UTC, Abbas-Abdulrab submitted a review, later dismissed

2024-03-12 06:53 UTC, Rudainasaleh approved these changes

2024-03-12 07:05 UTC, CodelineAtyab requested changes

2024-03-12 07:05 UTC, CodelineAtyab commented on examples/Sughiyas_work_area/genz_134_Palindrome_Verification_Tool.py
Lets use meaningful variable names

2024-03-12 07:36 UTC, Rudainasaleh submitted a review, later dismissed

2024-03-12 08:07 UTC, Abbas-Abdulrab submitted a review, later dismissed

2024-03-12 08:14 UTC, Alhasan-AJ submitted a review, later dismissed

2024-03-13 05:34 UTC, CodelineAtyab requested changes
Please use meaningful variable name and inline comments so anyhone can understand the code without dry running it.

2024-03-13 09:36 UTC, Rudainasaleh approved these changes

2024-03-13 09:36 UTC, Abbas-Abdulrab approved these changes

2024-03-14 05:12 UTC, Alhasan-AJ approved these changes

2024-03-14 05:13 UTC, aljab017 approved these changes

2024-03-14 05:13 UTC, sarah-alshukaily approved these changes

2024-03-14 05:14 UTC, aljab017 approved these changes

2024-03-14 05:29 UTC, merged