Genzsprtwo-27 : File Type-Based Directory Organizer
CodelineAtyab/genz-todo-list-app pull request #157
Opened 2024-03-20 06:46 UTC by Rudainasaleh

2024-03-20 06:59 UTC, Rudainasaleh commented
![](https://github.trello.services/images/mini-trello-icon.png) [File Type-Based Directory Organizer](https://trello.com/c/j8vsudS6/27-file-type-based-directory-organizer)

2024-03-20 07:24 UTC, sarah-alshukaily approved these changes

2024-03-20 07:28 UTC, aljab017 approved these changes

2024-03-20 07:50 UTC, Sughiya-AlSaid submitted a review, later dismissed

2024-03-25 06:14 UTC, CodelineAtyab commented on examples/Rudaina_work_area/Type-Based Directory/genzsprtwo_27_dir_orgnizer.py
> +import os
We can make use of shutil module, which is specifically designed for high level file operations and gives us a easy to use interface and advance operations which would require multiple steps and validation using the os module.

2024-03-25 06:15 UTC, CodelineAtyab commented on examples/Rudaina_work_area/Type-Based Directory/genzsprtwo_27_dir_orgnizer.py
> +        jpg_file_num += 1
glob can also help count files with specific extensions

2024-03-25 06:15 UTC, CodelineAtyab requested changes
Please check my comments

2024-03-26 07:15 UTC, Alhasan-AJ reviewed
good job Rudaina!!

2024-03-26 07:16 UTC, CodelineAtyab commented on examples/Rudaina_work_area/Type-Based Directory/genzsprtwo_27_dir_orgnizer.py
> +DIRECTORY = "./dir"
I believe STATIC_FILES_DIR will make much more sense

2024-03-26 07:17 UTC, CodelineAtyab commented on examples/Rudaina_work_area/Type-Based Directory/genzsprtwo_27_dir_orgnizer.py
> +def dir_organizer(source_dir):
I believe this is creating directories instead of organizing it so we can name it something like, create_dirs_if_not_exists

2024-03-26 07:25 UTC, CodelineAtyab commented on examples/Rudaina_work_area/Type-Based Directory/genzsprtwo_27_dir_orgnizer.py
> +    for file in files:
I believe this part is organizing the files so we can separate it out into another function. We can do this to achieve high cohesion and low coupling.
Or in simple terms "reduce dependency" and encourage single responsibility.

2024-03-26 07:26 UTC, CodelineAtyab requested changes
Please see my comments

2024-03-27 06:23 UTC, HaithamAlMaamari submitted a review, later dismissed

2024-03-27 06:45 UTC, jnulia approved these changes

2024-03-27 06:45 UTC, Sughiya-AlSaid approved these changes

2024-03-27 07:01 UTC, CodelineAtyab approved these changes
Good Work!

2024-03-27 07:02 UTC, merged