Feature/File Integrity/genzsprtwo-40
CodelineAtyab/genz-todo-list-app pull request #173
Opened 2024-03-27 07:35 UTC by Abbas-Abdulrab

2024-03-27 07:35 UTC, Abbas-Abdulrab commented
![](https://github.trello.services/images/mini-trello-icon.png) [File Integrity Checker](https://trello.com/c/Dxpz0Eru/40-file-integrity-checker)

2024-03-28 05:28 UTC, CodelineAtyab commented on examples/abbas_work_area/file_integrity.py
> +        for blocks in iter(lambda: input_file.read(4096), b""):
Please provide comments so a dev understands waht b"" is doing as a second argument to iter(), also if we are reading the file as "rb", do we need it ?

2024-03-28 05:30 UTC, CodelineAtyab commented on examples/abbas_work_area/file_integrity.py
> +    if original == new_sha256:
This should not work, because we should be comparing a hash with a hash and not file content with a hash.

2024-03-28 05:31 UTC, CodelineAtyab requested changes
Please check comments

2024-03-28 05:45 UTC, CodelineAtyab approved these changes
Great work reading the file content in chunks

2024-03-28 05:46 UTC, sarah-alshukaily approved these changes

2024-03-28 05:46 UTC, aaziz9 approved these changes

2024-03-28 05:46 UTC, Sughiya-AlSaid approved these changes
good job

2024-03-28 05:46 UTC, merged

2024-04-04 07:58 UTC, aljab017 commented
![](https://github.trello.services/images/mini-trello-icon.png) [OOP-Based Contact Book Management System Redesign](https://trello.com/c/TnNOdLbv/8-oop-based-contact-book-management-system-redesign)