genzsprfour-10: Implementing Pickle for Data Persistence in TODO List App
CodelineAtyab/genz-todo-list-app pull request #213
Opened 2024-04-22 09:24 UTC by aljab017

2024-04-22 09:24 UTC, aljab017 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementing Pickle for Data Persistence in TODO List App](https://trello.com/c/A6CMtb9V/10-implementing-pickle-for-data-persistence-in-todo-list-app)

2024-04-22 09:36 UTC, CodelineAtyab requested changes
It would be great if we also create a function to LOAD the object from the pickle file.

2024-04-23 04:53 UTC, HaithamAlMaamari approved these changes

2024-04-23 05:51 UTC, CodelineAtyab approved these changes

2024-04-23 05:52 UTC, ziyadabd approved these changes

2024-04-23 05:52 UTC, Rudainasaleh approved these changes

2024-04-23 05:52 UTC, merged