86epb0vee: Directory monitor and event based file handler
CodelineAtyab/genz-todo-list-app pull request #233
Opened 2024-05-12 07:09 UTC by Abbas-Abdulrab

## Summary of Change

## Link to User Story

## How to Test

## How to Revert

## Additional Notes

2024-05-12 07:09 UTC, CodelineAtyab commented
Task linked: [CU-86epb0vee Directory monitor and event based file handler](https://app.clickup.com/t/86epb0vee)

2024-05-12 07:13 UTC, sarah-alshukaily approved these changes

2024-05-12 07:40 UTC, CodelineAtyab requested changes

2024-05-12 07:40 UTC, CodelineAtyab commented on examples/abbas_work_area/check_thread.py
> +    existing_hashes = get_existing_hashes() or set()
If we load hashes from a file while processing each and every file, it can add up in a lot of delay with increasing number of files.

2024-05-12 07:40 UTC, CodelineAtyab commented on examples/abbas_work_area/check_thread.py
> +    content.append(data)
shouldn't we use content_lock here also ?

2024-05-12 07:55 UTC, HaithamAlMaamari approved these changes

2024-05-13 05:09 UTC, CodelineAtyab approved these changes

2024-05-13 05:10 UTC, aaziz9 approved these changes

2024-05-13 05:11 UTC, ziyadabd approved these changes

2024-05-14 03:26 UTC, merged