GenZ-108: Added a solution for the missing element task.
CodelineAtyab/genz-todo-list-app pull request #67
Opened 2024-03-10 11:03 UTC by Alhasan-AJ

2024-03-10 11:04 UTC, CodelineAtyab commented on examples/alhasan_work_area/fibonacci.py
> +    for i in range(lst[0],lst[-1]+1):
PEP-8: Lets put a space after ,

2024-03-10 11:04 UTC, CodelineAtyab commented on examples/alhasan_work_area/missing_element.py
> +    for i in range(lst[0],lst[-1]+1):
PEP-8: Lets put a space after ,

2024-03-10 11:04 UTC, CodelineAtyab commented on examples/alhasan_work_area/missing_element.py
> +print(missing_element([1,2,3,5,6]))
PEP-8: Lets put a space after ,

2024-03-10 11:04 UTC, ziyadabd submitted a review, later dismissed

2024-03-10 11:04 UTC, CodelineAtyab requested changes
Please see the comments

2024-03-10 11:06 UTC, sarah-alshukaily approved these changes

2024-03-10 11:35 UTC, Sughiya-AlSaid approved these changes

2024-03-11 05:49 UTC, CodelineAtyab commented on examples/alhasan_work_area/missing_element.py
> +def missing_element(lst):
Please consider adding a multiline comment to describe what this module is doing. For Example:
"""
This module contains a function that takes a list of unique integers in a specific range as input and returns the missing element as an output
"""

2024-03-11 05:49 UTC, CodelineAtyab commented on examples/alhasan_work_area/missing_element.py
> +    for n in lst:
Please rename "n" OR put an inline comment that tells the devs, what n could be. Is it an integer coming from lst or something else ?

2024-03-11 05:50 UTC, CodelineAtyab requested changes
Great work using meaningful variable names. However there are a few suggestions. Please respond to those

2024-03-11 07:05 UTC, Abbas-Abdulrab approved these changes

2024-03-12 06:26 UTC, CodelineAtyab approved these changes
Great Logic!

2024-03-12 06:43 UTC, aljab017 approved these changes

2024-03-12 06:43 UTC, sarah-alshukaily approved these changes

2024-03-12 06:44 UTC, merged