palindrome verfication
CodelineAtyab/genz-todo-list-app pull request #72
Opened 2024-03-10 11:31 UTC by Abbas-Abdulrab

2024-03-11 05:12 UTC, Rudainasaleh approved these changes

2024-03-11 05:23 UTC, sarah-alshukaily submitted a review, later dismissed

2024-03-11 05:40 UTC, CodelineAtyab commented on examples/abbas_work_area/palindrome.py
> +user = input("Enter: ").strip().replace(" ", "").lower()
Please consider using a meaningful variable name like user_input or something else

2024-03-11 05:41 UTC, CodelineAtyab commented on examples/abbas_work_area/palindrome.py
> +punc = []
Please consider using a meaningful variable name like list_of_punctuation_characters or something like this

2024-03-11 05:41 UTC, CodelineAtyab commented on examples/abbas_work_area/palindrome.py
> +remove = "".join(punc)
string_without_punctuation or something like this

2024-03-11 05:42 UTC, CodelineAtyab commented on examples/abbas_work_area/palindrome.py
> +punc1 = punc[::-1]
Please add comments to make it clear, what is being done here

2024-03-11 05:43 UTC, CodelineAtyab commented on examples/abbas_work_area/palindrome.py
> +    print("True")
Lets put this logic in a function and return True OR False from that function

2024-03-11 05:43 UTC, CodelineAtyab requested changes
Please respond to comments

2024-03-11 06:52 UTC, ziyadabd approved these changes

2024-03-11 07:03 UTC, aaziz9 approved these changes

2024-03-12 04:24 UTC, Sughiya-AlSaid approved these changes

2024-03-12 04:43 UTC, CodelineAtyab approved these changes
Nice!

2024-03-12 06:51 UTC, merged