Genz103
CodelineAtyab/genz-todo-list-app pull request #80
Opened 2024-03-11 05:59 UTC by ziyadabd

2024-03-11 06:09 UTC, Alhasan-AJ approved these changes
Nice work Ziyad!

2024-03-12 07:14 UTC, jnulia approved these changes

2024-03-13 05:38 UTC, CodelineAtyab requested changes
PLease refactor with info that would help devs understand the code better

2024-03-14 05:10 UTC, Alhasan-AJ approved these changes
Useful comments used.

2024-03-14 05:12 UTC, sarah-alshukaily approved these changes

2024-03-14 05:13 UTC, HaithamAlMaamari approved these changes

2024-03-14 05:32 UTC, CodelineAtyab approved these changes

2024-03-14 05:32 UTC, merged